name: Create Demo Branch

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  create_demo_branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.CREATE_BRANCH }}

      - name: Create and push demo branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b demo
          git push --force origin demo
